# theme: jekyll-theme-minimal
name: Jahi Grant
title: Portfolio
description: JavaScript, Python, HTML, CSS and other coding in the day of the life of a frontend developer
site_path: https://jahigrant.github.io/
include: ['_about_pages', '_javascript_projects', '_python_projects']
relative_permalinks: false