# theme: jekyll-theme-minimal
name: Jahi Grant
first_name: Jahi
last_name: Grant
title: Designs
strapline_text: Creating stylish, functional, high quality pieces. Each product designed is a unique product.
strapline:
  - Projets
  - Designs
  - musings
description: Creating stylish, functional, high quality pieces. Each product designed is a unique product.
site_path: https://jahigrant.github.io/
include: ['_about_pages']
relative_permalinks: false
copyright:
  start_year: 2000
  timezone: GMT
  city: London
  country: UK